//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bewise.MMEWebDeploymentHelpers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bewise.MMEWebDeploymentHelpers.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach debugger to all IIS Application pools.
        /// </summary>
        internal static string AttachToIssTitle {
            get {
                return ResourceManager.GetString("AttachToIssTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy to GAC.
        /// </summary>
        internal static string CopyToGacTitle {
            get {
                return ResourceManager.GetString("CopyToGacTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while attaching to all IIS Application pools.
        /// </summary>
        internal static string ErrorMsgAttachIis {
            get {
                return ResourceManager.GetString("ErrorMsgAttachIis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while copying to GAC.
        /// </summary>
        internal static string ErrorMsgCopyGac {
            get {
                return ResourceManager.GetString("ErrorMsgCopyGac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while recycling pools.
        /// </summary>
        internal static string ErrorMsgRecycle {
            get {
                return ResourceManager.GetString("ErrorMsgRecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Deployment Helpers.
        /// </summary>
        internal static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Deployment Helpers.
        /// </summary>
        internal static string OutputPaneTitle {
            get {
                return ResourceManager.GetString("OutputPaneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The output project is not an ClassLibrary. This tool is only available on ClassLibrary projects.
        /// </summary>
        internal static string OutputProjectNotADll {
            get {
                return ResourceManager.GetString("OutputProjectNotADll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle All IIS Application pools.
        /// </summary>
        internal static string RecyclePoolsTitle {
            get {
                return ResourceManager.GetString("RecyclePoolsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attaching to processes....
        /// </summary>
        internal static string StartAttachProcess {
            get {
                return ResourceManager.GetString("StartAttachProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuilding....
        /// </summary>
        internal static string StartBuildMsg {
            get {
                return ResourceManager.GetString("StartBuildMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying to GAC....
        /// </summary>
        internal static string StartCopyGac {
            get {
                return ResourceManager.GetString("StartCopyGac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycling....
        /// </summary>
        internal static string StartRecycle {
            get {
                return ResourceManager.GetString("StartRecycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully attached to all IIS Application pools.
        /// </summary>
        internal static string SuccessMsgAttachIis {
            get {
                return ResourceManager.GetString("SuccessMsgAttachIis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully copying to GAC.
        /// </summary>
        internal static string SuccessMsgCopyGac {
            get {
                return ResourceManager.GetString("SuccessMsgCopyGac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully recycling pools.
        /// </summary>
        internal static string SuccessMsgRecycle {
            get {
                return ResourceManager.GetString("SuccessMsgRecycle", resourceCulture);
            }
        }
    }
}
